
package(default_visibility=["//visibility:public"])

load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "add",
    module_name = "@demo/add",
    srcs = ["index.ts"],
    deps = ["@npm//@types/node"]
)